import { randomUUID } from 'node:crypto';
import { expect } from 'bun:test';
import { MikroORM } from '@mikro-orm/postgresql';
import { buildMikroOrmConfig } from '../../../../src/infrastructure/persistence/mikro-orm.config.js';
import { integrationConfig } from '../../support/integration-config.js';

/**
 * Raw SQL helpers for the schema tests. The point of these tests is the database on
 * its own: no domain, no ORM entities, just statements that try to break a rule and
 * the exact constraint or trigger that refuses them.
 */

/** SQLSTATE codes the tests assert on. */
export const SqlState = {
  UniqueViolation: '23505',
  CheckViolation: '23514',
  ForeignKeyViolation: '23503',
  RestrictViolation: '23001',
  DeadlockDetected: '40P01',
} as const;

/** Opens the ORM on wagering_test and applies pending migrations (no-op when already migrated). */
export async function openMigratedDatabase(): Promise<MikroORM> {
  const orm = await MikroORM.init({
    ...buildMikroOrmConfig(integrationConfig().database),
    debug: false,
  });
  await orm.migrator.up();
  return orm;
}

type SqlValue = string | number | null;
export type Row = Record<string, SqlValue>;

/** Literal for test values only (ids and amounts generated by the tests themselves). */
function literal(value: SqlValue): string {
  if (value === null) return 'null';
  if (typeof value === 'number') return String(value);
  return `'${value.replaceAll("'", "''")}'`;
}

export function insert(table: string, row: Row): string {
  const columns = Object.keys(row);
  return `insert into ${table} (${columns.join(', ')}) values (${columns.map((column) => literal(row[column] ?? null)).join(', ')})`;
}

export function update(table: string, id: string, changes: Row): string {
  const assignments = Object.entries(changes).map(([column, value]) => `${column} = ${literal(value)}`);
  return `update ${table} set ${assignments.join(', ')} where id = ${literal(id)}`;
}

/**
 * Runs the statements as ONE implicit transaction: several statements in a single
 * simple-protocol query string are committed together or not at all, and deferred
 * constraint triggers run at that commit. Nothing stays open on the pooled connection.
 */
export async function runInOneTransaction(orm: MikroORM, ...statements: string[]): Promise<void> {
  await orm.em.getConnection().execute(statements.join(';\n'));
}

export async function query<T>(orm: MikroORM, sql: string): Promise<T[]> {
  return orm.em.getConnection().execute<T[]>(sql);
}

/** Asserts the statement failed with this SQLSTATE and this constraint (or trigger) name. */
export async function expectViolation(
  attempt: Promise<unknown>,
  expected: { code: string; constraint: string },
): Promise<void> {
  const error = await attempt.then(
    () => undefined,
    (caught: unknown) => caught,
  );
  expectDatabaseError(error, expected);
}

/** Same check for an error already caught (e.g. from a statement that ran on a dedicated connection). */
export function expectDatabaseError(error: unknown, expected: { code: string; constraint?: string }): void {
  expect(error).toBeDefined();
  const actual = { code: sqlStateOf(error), constraint: (error as { constraint?: string }).constraint };
  expect(expected.constraint === undefined ? { code: actual.code } : actual).toEqual(expected);
}

/**
 * SQLSTATE of a database error. The MikroORM exception (pg driver) carries it in `code`;
 * Bun's SQL client puts it in `errno` and uses `code` for its own error kind.
 */
export function sqlStateOf(error: unknown): string | undefined {
  const { code, errno } = error as { code?: unknown; errno?: unknown };
  if (typeof errno === 'string') return errno;
  return typeof code === 'string' ? code : undefined;
}

export const AT = '2026-10-06T12:00:00.000Z';
export const HASH = 'a'.repeat(64);

export function newId(): string {
  return randomUUID();
}

export interface WalletRef {
  readonly id: string;
  readonly playerId: string;
}

export function walletRow(overrides: Row = {}): Row {
  return {
    id: newId(),
    player_id: newId(),
    currency: 'BRL',
    balance_amount: '0.00',
    version: 1,
    created_at: AT,
    updated_at: AT,
    ...overrides,
  };
}

/** A wallet with balance 0.00: needs no ledger entry, so it is valid on its own. */
export async function createEmptyWallet(orm: MikroORM): Promise<WalletRef> {
  const row = walletRow();
  await runInOneTransaction(orm, insert('wallets', row));
  return { id: String(row.id), playerId: String(row.player_id) };
}

/** A BET row for the wallet, PENDING by default. Overrides change any column. */
export function transactionRow(wallet: WalletRef, overrides: Row = {}): Row {
  const externalTransactionId = `ext-${newId()}`;
  return {
    id: newId(),
    provider_id: 'provider-a',
    external_transaction_id: externalTransactionId,
    idempotency_key: `provider-a:${externalTransactionId}`,
    payload_hash: HASH,
    wallet_id: wallet.id,
    player_id: wallet.playerId,
    round_id: 'round-1',
    game_id: 'fortune-chimp',
    kind: 'BET',
    amount: '25.00',
    currency: 'BRL',
    status: 'PENDING',
    created_at: AT,
    updated_at: AT,
    ...overrides,
  };
}

/** Columns that make a row a valid PROCESSED one. */
export function processed(resultBalance = '0.00'): Row {
  return {
    status: 'PROCESSED',
    processed_at: AT,
    result_balance_amount: resultBalance,
    result_balance_currency: 'BRL',
  };
}

export function ledgerRow(overrides: Row): Row {
  return {
    id: newId(),
    currency: 'BRL',
    created_at: AT,
    ...overrides,
  };
}

/**
 * Opens a wallet with a positive balance exactly as the application will: wallet row,
 * OPENING transaction and its CREDIT entry (0.00 -> balance, version 1) in one commit.
 */
export async function openWalletWithBalance(
  orm: MikroORM,
  balance: string,
  ids: { id?: string; playerId?: string } = {},
): Promise<WalletRef & { openingId: string }> {
  const wallet = walletRow({
    balance_amount: balance,
    ...(ids.id === undefined ? {} : { id: ids.id }),
    ...(ids.playerId === undefined ? {} : { player_id: ids.playerId }),
  });
  const ref = { id: String(wallet.id), playerId: String(wallet.player_id) };
  const opening = transactionRow(ref, {
    provider_id: 'internal',
    external_transaction_id: `opening-${ref.id}`,
    idempotency_key: `internal:opening-${ref.id}`,
    payload_hash: null,
    round_id: null,
    game_id: null,
    kind: 'OPENING',
    amount: balance,
    ...processed(balance),
  });
  await runInOneTransaction(
    orm,
    insert('wallets', wallet),
    insert('wager_transactions', opening),
    insert(
      'wallet_ledger_entries',
      ledgerRow({
        wallet_id: ref.id,
        transaction_id: String(opening.id),
        direction: 'CREDIT',
        amount: balance,
        balance_before: '0.00',
        balance_after: balance,
        wallet_version: 1,
      }),
    ),
  );
  return { ...ref, openingId: String(opening.id) };
}

/**
 * Statements for one processed movement, the way Slice 2 will write it:
 * transaction row, ledger entry and wallet update.
 */
export function movementStatements(
  wallet: WalletRef,
  movement: { direction: 'DEBIT' | 'CREDIT'; amount: string; before: string; after: string; version: number },
  transactionOverrides: Row = {},
): { transactionId: string; statements: string[] } {
  const transaction = transactionRow(wallet, {
    kind: movement.direction === 'DEBIT' ? 'BET' : 'WIN',
    amount: movement.amount,
    ...processed(movement.after),
    ...transactionOverrides,
  });
  const transactionId = String(transaction.id);
  return {
    transactionId,
    statements: [
      insert('wager_transactions', transaction),
      insert(
        'wallet_ledger_entries',
        ledgerRow({
          wallet_id: wallet.id,
          transaction_id: transactionId,
          direction: movement.direction,
          amount: movement.amount,
          balance_before: movement.before,
          balance_after: movement.after,
          wallet_version: movement.version,
        }),
      ),
      update('wallets', wallet.id, { balance_amount: movement.after, version: movement.version, updated_at: AT }),
    ],
  };
}
